schema_version: 0.1
type: producer
identifier: xml
title: XML File
version: 1
copyright: Ushodaya Enterprises Limited
creator: Dan Dennedy
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
description: |
  Construct a service network from an XML description. See docs/mlt-xml.txt.
parameters:
  - identifier: argument
    title: URL
    type: string
    description: |
      An XML text file containing MLT XML
      Since MLT XML files can be parameterised, the URL syntax is:
      {file-name}[?{param-name}{'='|':'}{param-value}[&{param-name}{'='|':'}{param-value}...]]
      A colon is allowed instead of an equal sign to pacify melt, who tokenises 
      anything with an equal sign as a property setting. Also, when running 
      melt from the shell, beware of the '?' and shell filename expansion. You 
      can surround the URL with single quotations to prevent expansion. 
      Finally, the loader will fail to match the filename when you use 
      parameters, so preface the url with 'xml:' to force the loader to load 
      with the xml service.
    readonly: no
    required: yes
    mutable: no
    widget: fileopen
    
  - identifier: resource
    title: Resource
    type: string
    description: File location. See "argument" above.
    readonly: yes
